paths:
  /api/drivers:
    get:
      summary: Get a list of all drivers
      tags: [ Drivers ]
      responses:
        200:
          description: List of all drivers
    post:
      summary: Add a new driver
      tags: [ Drivers ]
      responses:
        201:
          description: The driver was successfully created
        400:
          description: Validation error