export const projects = [
  {
    id: 4,
    usedUId: 0,
    name: "p1_ze2nB6jpQEmVbsYTbSAqQKZ2",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/p1_ze2nB6jpQEmVbsYTbSAqQKZ2",
    linkName: "p1",
    linkPath: "СПА/Проекты/Medvedev/p1",
    modelsId: [113],
    isTemplate: false,
  },
  {
    id: 5,
    usedUId: 0,
    name: "Ponomarev_tgNVVCDQr1uNJC4edg2am336",
    path: "/home/dmitrii/.kvant_remote/СПА/Проекты/Ponomarev_tgNVVCDQr1uNJC4edg2am336",
    linkName: "Ponomarev",
    linkPath: "СПА/Проекты/Ponomarev",
    modelsId: [87, 85],
    isTemplate: false,
  },
  {
    id: 8,
    usedUId: 0,
    name: "пустой шаблон_HmFWYiQiDl0twGRc4F2wH2nD",
    path: "/home/lazarev/.kvant_remote/СПА/Шаблоны/Проекты/пустой шаблон_HmFWYiQiDl0twGRc4F2wH2nD",
    linkName: "пустой шаблон",
    linkPath: "/СПА/Шаблоны/пустой шаблон",
    modelsId: [22],
    isTemplate: true,
  },
  {
    id: 10,
    usedUId: 0,
    name: "ресемпл-оптикс-омр_0c965a22-b6d2-42da-9f38-d8ea668fbf9f",
    path: "/home/lazarev/.kvant_remote/СПА/Шаблоны/Подмодели/ресемпл-оптикс-омр_0c965a22-b6d2-42da-9f38-d8ea668fbf9f",
    linkName: "ресемпл-оптикс-омр",
    linkPath: "/СПА/Шаблоны/ресемпл-оптикс-омр",
    modelsId: [24],
    isTemplate: true,
  },
  {
    id: 13,
    usedUId: 0,
    name: "p3_WKEPWv14Wh1oSXa45xRgoifv",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/p3_WKEPWv14Wh1oSXa45xRgoifv",
    linkName: "p3",
    linkPath: "СПА/Проекты/Medvedev/p3",
    modelsId: null,
    isTemplate: false,
  },
  {
    id: 14,
    usedUId: 0,
    name: "автоэнкодер с лучшей моделью_5eea4c7c-3a09-4d02-94de-e8a088f4b0d6",
    path: "/home/dmitrii/.kvant_remote/СПА/Шаблоны/Подмодели/автоэнкодер с лучшей моделью_5eea4c7c-3a09-4d02-94de-e8a088f4b0d6",
    linkName: "автоэнкодер с лучшей моделью",
    linkPath: "/СПА/Шаблоны/автоэнкодер с лучшей моделью",
    modelsId: [26],
    isTemplate: true,
  },
  {
    id: 15,
    usedUId: 0,
    name: "автоэнкодер с лучшей моделью 2_724f1598-33db-4505-a24f-d86cdf2ceca5",
    path: "/home/dmitrii/.kvant_remote/СПА/Шаблоны/Подмодели/автоэнкодер с лучшей моделью 2_724f1598-33db-4505-a24f-d86cdf2ceca5",
    linkName: "автоэнкодер с лучшей моделью 2",
    linkPath: "/СПА/Шаблоны/автоэнкодер с лучшей моделью 2",
    modelsId: [27],
    isTemplate: true,
  },
  {
    id: 17,
    usedUId: 0,
    name: "шаблон цепочки предобработки_2fb12ebf-b153-4ad1-a20b-f290c3a68fc7",
    path: "/home/lazarev/.kvant_remote/СПА/Шаблоны/Подмодели/шаблон цепочки предобработки_2fb12ebf-b153-4ad1-a20b-f290c3a68fc7",
    linkName: "шаблон цепочки предобработки",
    linkPath: "/СПА/Шаблоны/шаблон цепочки предобработки",
    modelsId: [43],
    isTemplate: true,
  },
  {
    id: 19,
    usedUId: 0,
    name: "шаблон цепочки предобработки (1)_bb3b8beb-9336-4964-bd16-52d1c668dd50",
    path: "/home/lazarev/.kvant_remote/СПА/Шаблоны/Подмодели/шаблон цепочки предобработки (1)_bb3b8beb-9336-4964-bd16-52d1c668dd50",
    linkName: "шаблон цепочки предобработки (1)",
    linkPath: "/СПА/Шаблоны/шаблон цепочки предобработки (1)",
    modelsId: [45],
    isTemplate: true,
  },
  {
    id: 20,
    usedUId: 0,
    name: "mset_75252503-25fe-4ace-aa94-df499f34428d",
    path: "/home/lazarev/.kvant_remote/СПА/Шаблоны/Подмодели/mset_75252503-25fe-4ace-aa94-df499f34428d",
    linkName: "mset",
    linkPath: "/СПА/Шаблоны/mset",
    modelsId: [58],
    isTemplate: true,
  },
  {
    id: 21,
    usedUId: 0,
    name: "mset - 2_449811ec-0d45-4bd7-9f48-e1582743d4ef",
    path: "/home/lazarev/.kvant_remote/СПА/Шаблоны/Подмодели/mset - 2_449811ec-0d45-4bd7-9f48-e1582743d4ef",
    linkName: "mset - 2",
    linkPath: "/СПА/Шаблоны/mset - 2",
    modelsId: [59],
    isTemplate: true,
  },
  {
    id: 22,
    usedUId: 0,
    name: "шаблон мсет_agMXOTilaAImvULq02Sl4Iu6",
    path: "/home/lazarev/.kvant_remote/СПА/Шаблоны/Модели/шаблон мсет_agMXOTilaAImvULq02Sl4Iu6",
    linkName: "шаблон мсет",
    linkPath: "/СПА/Шаблоны/шаблон мсет",
    modelsId: [60],
    isTemplate: true,
  },
  {
    id: 23,
    usedUId: 0,
    name: "vae_6af5ec6b-b62c-46f0-8a40-3d162bfed9fe",
    path: "/home/lazarev/.kvant_remote/СПА/Шаблоны/Подмодели/vae_6af5ec6b-b62c-46f0-8a40-3d162bfed9fe",
    linkName: "vae",
    linkPath: "/СПА/Шаблоны/vae",
    modelsId: [62],
    isTemplate: true,
  },
  {
    id: 28,
    usedUId: 0,
    name: "Турбина Демо_IqLMN5Y6vMUVxq2QTPng0qAk",
    path: "/home/lazarev/.kvant_remote/СПА/Проекты/Турбина Демо_IqLMN5Y6vMUVxq2QTPng0qAk",
    linkName: "Турбина Демо",
    linkPath: "СПА/Проекты/Турбина Демо",
    modelsId: [120, 89, 121, 75, 131, 119, 129, 77, 76, 78],
    isTemplate: false,
  },
  {
    id: 31,
    usedUId: 0,
    name: "123123_47d72a49-fdf9-4ba1-905e-60085d1f03eb",
    path: "/home/lazarev/.kvant_remote/СПА/Шаблоны/Подмодели/123123_47d72a49-fdf9-4ba1-905e-60085d1f03eb",
    linkName: "123123",
    linkPath: "/СПА/Шаблоны/123123",
    modelsId: [80],
    isTemplate: true,
  },
  {
    id: 32,
    usedUId: 0,
    name: "test 21.05_TeR7mCeSqBLiWCZZEeUeVFvX",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/test 21.05_TeR7mCeSqBLiWCZZEeUeVFvX",
    linkName: "test 21.05",
    linkPath: "СПА/Проекты/Тестирование/Orlov/test 21.05",
    modelsId: [100, 81, 98, 82, 90],
    isTemplate: false,
  },
  {
    id: 34,
    usedUId: 0,
    name: "пустой_E6HitJBCqdvZPW3r0HLJnVex",
    path: "/home/lazarev/.kvant_remote/СПА/Проекты/пустой_E6HitJBCqdvZPW3r0HLJnVex",
    linkName: "пустой",
    linkPath: "СПА/Проекты/пустой",
    modelsId: [94, 92, 96, 91],
    isTemplate: false,
  },
  {
    id: 35,
    usedUId: 0,
    name: "шаблон с кроссвалидацией_26d86601-7cda-4615-97df-dc0ce7352b8c",
    path: "/home/lazarev/.kvant_remote/СПА/Шаблоны/Подмодели/шаблон с кроссвалидацией_26d86601-7cda-4615-97df-dc0ce7352b8c",
    linkName: "шаблон с кроссвалидацией",
    linkPath: "/СПА/Шаблоны/шаблон с кроссвалидацией",
    modelsId: [93],
    isTemplate: true,
  },
  {
    id: 36,
    usedUId: 0,
    name: "шаблон модели с кроссвалидацией_MdOwfpR6VaatZNdGz4ta899N",
    path: "/home/lazarev/.kvant_remote/СПА/Шаблоны/Модели/шаблон модели с кроссвалидацией_MdOwfpR6VaatZNdGz4ta899N",
    linkName: "шаблон модели с кроссвалидацией",
    linkPath: "/СПА/Шаблоны/шаблон модели с кроссвалидацией",
    modelsId: [95],
    isTemplate: true,
  },
  {
    id: 39,
    usedUId: 0,
    name: "air_intake_oi7U9xYptQpl2V9c6a3149Ts",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/air_intake_oi7U9xYptQpl2V9c6a3149Ts",
    linkName: "air_intake",
    linkPath: "СПА/Проекты/GT_ALSTOM/air_intake",
    modelsId: [103, 104],
    isTemplate: false,
  },
  {
    id: 40,
    usedUId: 0,
    name: "combustion_chamber_w7XikrjHt1hwNtc9EkAiON3n",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/combustion_chamber_w7XikrjHt1hwNtc9EkAiON3n",
    linkName: "combustion_chamber",
    linkPath: "СПА/Проекты/GT_ALSTOM/combustion_chamber",
    modelsId: null,
    isTemplate: false,
  },
  {
    id: 41,
    usedUId: 0,
    name: "compressor_LsU1JMLZPEN4XC2vqKnukysD",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/compressor_LsU1JMLZPEN4XC2vqKnukysD",
    linkName: "compressor",
    linkPath: "СПА/Проекты/GT_ALSTOM/compressor",
    modelsId: [102],
    isTemplate: false,
  },
  {
    id: 42,
    usedUId: 0,
    name: "gas_fuel_6ULbHLxNA0zHrSPGmxpsEr5e",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/gas_fuel_6ULbHLxNA0zHrSPGmxpsEr5e",
    linkName: "gas_fuel",
    linkPath: "СПА/Проекты/GT_ALSTOM/gas_fuel",
    modelsId: null,
    isTemplate: false,
  },
  {
    id: 43,
    usedUId: 0,
    name: "generator_2X0RqDUB5tnm5KkwkyNasTQT",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/generator_2X0RqDUB5tnm5KkwkyNasTQT",
    linkName: "generator",
    linkPath: "СПА/Проекты/GT_ALSTOM/generator",
    modelsId: [101, 99],
    isTemplate: false,
  },
  {
    id: 44,
    usedUId: 0,
    name: "lubricating_oil_jIiCK8VvrDABXudmif6lbYdv",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/lubricating_oil_jIiCK8VvrDABXudmif6lbYdv",
    linkName: "lubricating_oil",
    linkPath: "СПА/Проекты/GT_ALSTOM/lubricating_oil",
    modelsId: null,
    isTemplate: false,
  },
  {
    id: 45,
    usedUId: 0,
    name: "protection_system_kPl73vMSfSmtZGc7xV2J5Z6j",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/protection_system_kPl73vMSfSmtZGc7xV2J5Z6j",
    linkName: "protection_system",
    linkPath: "СПА/Проекты/GT_ALSTOM/protection_system",
    modelsId: null,
    isTemplate: false,
  },
  {
    id: 46,
    usedUId: 0,
    name: "turbine_mFELQE9jEeamhIsBX8chC1Kv",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/turbine_mFELQE9jEeamhIsBX8chC1Kv",
    linkName: "turbine",
    linkPath: "СПА/Проекты/GT_ALSTOM/turbine",
    modelsId: null,
    isTemplate: false,
  },
  {
    id: 48,
    usedUId: 0,
    name: "Alicen_eiOx5TRMsSNsNVKxJdkNt1r6",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/Alicen_eiOx5TRMsSNsNVKxJdkNt1r6",
    linkName: "Alicen",
    linkPath: "СПА/Проекты/Тестирование/Милованова/Alicen",
    modelsId: [105],
    isTemplate: false,
  },
  {
    id: 49,
    usedUId: 0,
    name: "newTempl_Bwr14H0N9QID273KrN1OKPgR",
    path: "/home/alex/.kvant_remote/СПА/Шаблоны/Проекты/newTempl_Bwr14H0N9QID273KrN1OKPgR",
    linkName: "newTempl",
    linkPath: "СПА/Шаблоны/Medvedev/newTempl",
    modelsId: null,
    isTemplate: true,
  },
  {
    id: 51,
    usedUId: 0,
    name: "GT_ALSTOM_NozOiofcSlLmsx4KKi9Qnbea",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/GT_ALSTOM_NozOiofcSlLmsx4KKi9Qnbea",
    linkName: "GT_ALSTOM",
    linkPath: "СПА/Проекты/ДЖЕТ ТГ/GT_ALSTOM",
    modelsId: [107, 108, 109, 112, 106],
    isTemplate: false,
  },
  {
    id: 55,
    usedUId: 0,
    name: "ChangePointDetection_0_EJ0mQP6h2FBcCi9c2A0Tcqk5",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/ChangePointDetection_0_EJ0mQP6h2FBcCi9c2A0Tcqk5",
    linkName: "ChangePointDetection",
    linkPath: "СПА/Проекты/Тестирование/Trykova/ChangePointDetection",
    modelsId: [110],
    isTemplate: false,
  },
  {
    id: 56,
    usedUId: 0,
    name: "MSET_3iqTskmnNyEoj9u0benwicNF",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/MSET_3iqTskmnNyEoj9u0benwicNF",
    linkName: "MSET",
    linkPath: "СПА/Проекты/Тестирование/Trykova/MSET",
    modelsId: [111],
    isTemplate: false,
  },
  {
    id: 60,
    usedUId: 0,
    name: "gg_oQgONyEJcRYnOG1tPqmUfB0c",
    path: "/home/alex/.kvant_remote/СПА/Проекты/gg_oQgONyEJcRYnOG1tPqmUfB0c",
    linkName: "gg",
    linkPath: "СПА/Проекты/Medvedev/gg",
    modelsId: [114],
    isTemplate: false,
  },
  {
    id: 62,
    usedUId: 0,
    name: "ffgg_mVrVbTaruMmzmcy6NWdq7iKU",
    path: "/home/alex/.kvant_remote/СПА/Проекты/ffgg_mVrVbTaruMmzmcy6NWdq7iKU",
    linkName: "ffgg",
    linkPath: "СПА/Проекты/Medvedev/ffgg",
    modelsId: [115],
    isTemplate: false,
  },
  {
    id: 63,
    usedUId: 0,
    name: "mytt",
    path: "/home/alex/.kvant_remote/СПА/Шаблоны/Подмодели/mytt",
    linkName: "mytt",
    linkPath: "СПА/Шаблоны/mytt",
    modelsId: [116],
    isTemplate: true,
  },
  {
    id: 65,
    usedUId: 0,
    name: "lk",
    path: "/home/alex/.kvant_remote/СПА/Шаблоны/Подмодели/lk",
    linkName: "lk",
    linkPath: "СПА/Шаблоны/lk",
    modelsId: [117],
    isTemplate: true,
  },
  {
    id: 66,
    usedUId: 0,
    name: "p123_SXoLYHni7E8WluTlxIe53IsT",
    path: "/home/alex/.kvant_remote/СПА/Проекты/p123_SXoLYHni7E8WluTlxIe53IsT",
    linkName: "p123",
    linkPath: "СПА/Проекты/Medvedev/p123",
    modelsId: [118],
    isTemplate: false,
  },
  {
    id: 67,
    usedUId: 0,
    name: "lklk_msPXG3p8lo1GXWc2qKehDYfO",
    path: "/home/alex/.kvant_remote/СПА/Проекты/lklk_msPXG3p8lo1GXWc2qKehDYfO",
    linkName: "lklk",
    linkPath: "СПА/Проекты/Medvedev/lklk",
    modelsId: null,
    isTemplate: false,
  },
  {
    id: 68,
    usedUId: 0,
    name: "OPTICS_v3e5waugYz14Qi9bwd6hwySN",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/OPTICS_v3e5waugYz14Qi9bwd6hwySN",
    linkName: "OPTICS",
    linkPath: "СПА/Проекты/Тестирование/Trykova/OPTICS",
    modelsId: [124],
    isTemplate: false,
  },
  {
    id: 71,
    usedUId: 0,
    name: "Autoencoder_KzE0lOcxNSad13gScRxM51FX",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/Autoencoder_KzE0lOcxNSad13gScRxM51FX",
    linkName: "Autoencoder",
    linkPath: "СПА/Проекты/Тестирование/Trykova/Autoencoder",
    modelsId: [122],
    isTemplate: false,
  },
  {
    id: 72,
    usedUId: 0,
    name: "DBSCAN_fK9VNjRQy0EoW9vzV3MO71KK",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/DBSCAN_fK9VNjRQy0EoW9vzV3MO71KK",
    linkName: "DBSCAN",
    linkPath: "СПА/Проекты/Тестирование/Trykova/DBSCAN",
    modelsId: [123],
    isTemplate: false,
  },
  {
    id: 73,
    usedUId: 0,
    name: "test_AE_646zQqV6LhzvYkQkMK59tjhS",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/test_AE_646zQqV6LhzvYkQkMK59tjhS",
    linkName: "test_AE",
    linkPath: "СПА/Проекты/kotsoev/test_AE",
    modelsId: [125, 126, 128],
    isTemplate: false,
  },
  {
    id: 74,
    usedUId: 0,
    name: "LSTM_9cfuvgnRGWcLNCKF94Q78yw2",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/LSTM_9cfuvgnRGWcLNCKF94Q78yw2",
    linkName: "LSTM",
    linkPath: "СПА/Проекты/Тестирование/Trykova/LSTM",
    modelsId: [127],
    isTemplate: false,
  },
  {
    id: 77,
    usedUId: 0,
    name: "123-123",
    path: "/home/lazarev/.kvant_remote/СПА/Шаблоны/Подмодели/123-123",
    linkName: "123-123",
    linkPath: "СПА/Шаблоны/123-123",
    modelsId: [132],
    isTemplate: true,
  },
  {
    id: 82,
    usedUId: 0,
    name: "Новый проект_3GWdeP6DBBXmr0padQ7fs9kh",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/Новый проект_3GWdeP6DBBXmr0padQ7fs9kh",
    linkName: "supran",
    linkPath: "СПА/Проекты/kotsoev/supran",
    modelsId: [136, 137, 199],
    isTemplate: false,
  },
  {
    id: 83,
    usedUId: 0,
    name: "РСА_BTSimu9HYzuXvAQeOUTZiggH",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/РСА_BTSimu9HYzuXvAQeOUTZiggH",
    linkName: "МетодГлавныхКомпонент",
    linkPath: "СПА/Проекты/Тестирование/Trykova/МетодГлавныхКомпонент",
    modelsId: [140],
    isTemplate: false,
  },
  {
    id: 85,
    usedUId: 0,
    name: "Хотеллинг_BkphCKYZCULVi5ojQWu3ig5u",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/Хотеллинг_BkphCKYZCULVi5ojQWu3ig5u",
    linkName: "КритерийХотеллингаТестировать",
    linkPath: "СПА/Проекты/Тестирование/Trykova/КритерийХотеллингаТестировать",
    modelsId: [139],
    isTemplate: false,
  },
  {
    id: 87,
    usedUId: 0,
    name: "СкользящееСреднее_rDKYzEdHbwT9j3hPcFprpOPf",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/СкользящееСреднее_rDKYzEdHbwT9j3hPcFprpOPf",
    linkName: "СкользящееСреднее",
    linkPath: "СПА/Проекты/Тестирование/Trykova/СкользящееСреднее",
    modelsId: [149],
    isTemplate: false,
  },
  {
    id: 89,
    usedUId: 0,
    name: "Ресемплирование_OB985LdMKeuF4QBLX6lbCz6j",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/Ресемплирование_OB985LdMKeuF4QBLX6lbCz6j",
    linkName: "Ресемплирование",
    linkPath: "СПА/Проекты/Тестирование/Trykova/Ресемплирование",
    modelsId: null,
    isTemplate: false,
  },
  {
    id: 90,
    usedUId: 0,
    name: "ОгибающаяГильберта_iOaYgqmBGZexM1rmV9JnAODk",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/ОгибающаяГильберта_iOaYgqmBGZexM1rmV9JnAODk",
    linkName: "ОгибающаяГильберта",
    linkPath: "СПА/Проекты/Тестирование/Trykova/ОгибающаяГильберта",
    modelsId: [143],
    isTemplate: false,
  },
  {
    id: 91,
    usedUId: 0,
    name: "ОбщееОтклонениеМодели_QpdZWif5xpLwEdDpQ7mdjUDU",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/ОбщееОтклонениеМодели_QpdZWif5xpLwEdDpQ7mdjUDU",
    linkName: "ОбщееОтклонениеМодели",
    linkPath: "СПА/Проекты/Тестирование/Trykova/ОбщееОтклонениеМодели",
    modelsId: [142],
    isTemplate: false,
  },
  {
    id: 92,
    usedUId: 0,
    name: "НормировкаСигналов_DbMLX7ywcpuO0hW9NGEpSWfn",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/НормировкаСигналов_DbMLX7ywcpuO0hW9NGEpSWfn",
    linkName: "НормировкаСигналов",
    linkPath: "СПА/Проекты/Тестирование/Trykova/НормировкаСигналов",
    modelsId: [141],
    isTemplate: false,
  },
  {
    id: 93,
    usedUId: 0,
    name: "ЗаполнениеПропусков_VR3Pef8OTD3ojcZnsfwQa0hw",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/ЗаполнениеПропусков_VR3Pef8OTD3ojcZnsfwQa0hw",
    linkName: "ЗаполнениеПропусков",
    linkPath: "СПА/Проекты/Тестирование/Trykova/ЗаполнениеПропусков",
    modelsId: [138],
    isTemplate: false,
  },
  {
    id: 94,
    usedUId: 0,
    name: "ff_RhyCiLXxgtAXnNDthEDgvbid",
    path: "/home/alex/.kvant_remote/СПА/Шаблоны/Проекты/ff_RhyCiLXxgtAXnNDthEDgvbid",
    linkName: "ff",
    linkPath: "СПА/Шаблоны/ff",
    modelsId: [145],
    isTemplate: true,
  },
  {
    id: 95,
    usedUId: 0,
    name: "ghgh_4irczv0et0MaivlSaWHsE5pj",
    path: "/home/alex/.kvant_remote/СПА/Шаблоны/Проекты/ghgh_4irczv0et0MaivlSaWHsE5pj",
    linkName: "ghgh",
    linkPath: "СПА/Шаблоны/ghgh",
    modelsId: [146],
    isTemplate: true,
  },
  {
    id: 99,
    usedUId: 0,
    name: "СкользящаяМедиана_hXMBhLd72J3WuDCuLxPXSpNx",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/СкользящаяМедиана_hXMBhLd72J3WuDCuLxPXSpNx",
    linkName: "СкользящаяМедиана",
    linkPath: "СПА/Проекты/Тестирование/Trykova/СкользящаяМедиана",
    modelsId: [148],
    isTemplate: false,
  },
  {
    id: 100,
    usedUId: 0,
    name: "УдалениеВыбросов_SAGGPILrYRBHrgpakfdtenu7",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/УдалениеВыбросов_SAGGPILrYRBHrgpakfdtenu7",
    linkName: "УдалениеВыбросов",
    linkPath: "СПА/Проекты/Тестирование/Trykova/УдалениеВыбросов",
    modelsId: [150],
    isTemplate: false,
  },
  {
    id: 101,
    usedUId: 0,
    name: "МодельХольтаВинтерса_9KEjudpJY63aAXPTmz8IgzuX",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/МодельХольтаВинтерса_9KEjudpJY63aAXPTmz8IgzuX",
    linkName: "МодельХольтаВинтерса",
    linkPath: "СПА/Проекты/Тестирование/Trykova/МодельХольтаВинтерса",
    modelsId: [155],
    isTemplate: false,
  },
  {
    id: 102,
    usedUId: 0,
    name: "ЛинейнаяРегрессия_loEtxEMavfVl6kkrwiJbwiig",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/ЛинейнаяРегрессия_loEtxEMavfVl6kkrwiJbwiig",
    linkName: "ЛинейнаяРегрессия",
    linkPath: "СПА/Проекты/Тестирование/Trykova/ЛинейнаяРегрессия",
    modelsId: [157],
    isTemplate: false,
  },
  {
    id: 103,
    usedUId: 0,
    name: "ВекторнаяАвторегрессия_YeNADKcb9cxFeR5GJJ9ze8MT",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/ВекторнаяАвторегрессия_YeNADKcb9cxFeR5GJJ9ze8MT",
    linkName: "ВекторнаяАвторегрессия",
    linkPath: "СПА/Проекты/Тестирование/Trykova/ВекторнаяАвторегрессия",
    modelsId: [158],
    isTemplate: false,
  },
  {
    id: 104,
    usedUId: 0,
    name: "САРИМА_9ndLrJxTZ4nfH4efeSToqgcv",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/САРИМА_9ndLrJxTZ4nfH4efeSToqgcv",
    linkName: "САРИМА",
    linkPath: "СПА/Проекты/Тестирование/Trykova/САРИМА",
    modelsId: [151],
    isTemplate: false,
  },
  {
    id: 105,
    usedUId: 0,
    name: "ЛСТМ_eE1XSnVPQpbrHliqyVyxCB7C",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/ЛСТМ_eE1XSnVPQpbrHliqyVyxCB7C",
    linkName: "ЛСТМ",
    linkPath: "СПА/Проекты/Тестирование/Trykova/ЛСТМ",
    modelsId: [156],
    isTemplate: false,
  },
  {
    id: 106,
    usedUId: 0,
    name: "ФильтрБаттерворта_BWbTFoQCJjRUfwFwqkPkhpyx",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/ФильтрБаттерворта_BWbTFoQCJjRUfwFwqkPkhpyx",
    linkName: "ФильтрБаттерворта",
    linkPath: "СПА/Проекты/Тестирование/Trykova/ФильтрБаттерворта",
    modelsId: [152],
    isTemplate: false,
  },
  {
    id: 107,
    usedUId: 0,
    name: "ФильтрХодрикаПрескотта_YpL3XlULhEpMN0Av9R0sKdh1",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/ФильтрХодрикаПрескотта_YpL3XlULhEpMN0Av9R0sKdh1",
    linkName: "ФильтрХодрикаПрескотта",
    linkPath: "СПА/Проекты/Тестирование/Trykova/ФильтрХодрикаПрескотта",
    modelsId: [154],
    isTemplate: false,
  },
  {
    id: 108,
    usedUId: 0,
    name: "ФильтрКалмана_kI4ZlsOW2QSRsRtxzf75ifgl",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/ФильтрКалмана_kI4ZlsOW2QSRsRtxzf75ifgl",
    linkName: "ФильтрКалмана",
    linkPath: "СПА/Проекты/Тестирование/Trykova/ФильтрКалмана",
    modelsId: [153],
    isTemplate: false,
  },
  {
    id: 110,
    usedUId: 0,
    name: "SAPRUN_0_ff5KcZNiAWuRbWiUYl3O9NKI",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/SAPRUN_0_ff5KcZNiAWuRbWiUYl3O9NKI",
    linkName: "SAPRUN_0",
    linkPath: "СПА/Проекты/Тестирование/Колозин/SAPRUN_0",
    modelsId: [202, 204],
    isTemplate: false,
  },
  {
    id: 111,
    usedUId: 0,
    name: "test_r4WTaAGyKYpLgtl6OxGpekqL",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/test_r4WTaAGyKYpLgtl6OxGpekqL",
    linkName: "test",
    linkPath: "СПА/Проекты/Тестирование/Лазарев/test",
    modelsId: [203, 163],
    isTemplate: false,
  },
  {
    id: 112,
    usedUId: 0,
    name: "X4_k1RkqPkNIgQad45fB8cvvLeV",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/X4_k1RkqPkNIgQad45fB8cvvLeV",
    linkName: "X4",
    linkPath: "СПА/Проекты/Тестирование/Колозин/X4",
    modelsId: null,
    isTemplate: false,
  },
  {
    id: 116,
    usedUId: 0,
    name: "Северсталь_BlwiWhRrZAyuAivElSkxVMFO",
    path: "/home/diaprom/.kvant_remote/СПА/Шаблоны/Проекты/Северсталь_BlwiWhRrZAyuAivElSkxVMFO",
    linkName: "Северсталь",
    linkPath: "СПА/Шаблоны/Северсталь",
    modelsId: [168, 169, 172, 170, 171, 167],
    isTemplate: true,
  },
  {
    id: 117,
    usedUId: 0,
    name: "SAPRUN_1_s2kQTzfBFIcUgksnlfyAzCMI",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/SAPRUN_1_s2kQTzfBFIcUgksnlfyAzCMI",
    linkName: "SAPRUN_1",
    linkPath: "СПА/Проекты/Тестирование/Журавлев/SAPRUN_1",
    modelsId: null,
    isTemplate: false,
  },
  {
    id: 118,
    usedUId: 0,
    name: "SAPRUN_2_cXIgDGYhlJLAl7Lju8u8Uwrg",
    path: "/home/diaprom/.kvant_remote/СПА/Проекты/SAPRUN_2_cXIgDGYhlJLAl7Lju8u8Uwrg",
    linkName: "SAPRUN_2",
    linkPath: "СПА/Проекты/Тестирование/Молчанов/SAPRUN_2",
    modelsId: null,
    isTemplate: false,
  },
  {
    id: 119,
    usedUId: 0,
    name: "Exhauster 6_2_BKF2flF0HLssDoz7FXYKVHwZ",
    path: "/home/diaprom/.kvant_remote/СПА/Шаблоны/Модели/Exhauster 6_2_BKF2flF0HLssDoz7FXYKVHwZ",
    linkName: "Exhauster 6_2",
    linkPath: "СПА/Шаблоны/Exhauster 6_2",
    modelsId: [190],
    isTemplate: true,
  },
  {
    id: 120,
    usedUId: 0,
    name: "exhauster_4_2_8JLWrlAyC98J6a10V9oBqpJ5",
    path: "/home/diaprom/.kvant_remote/СПА/Шаблоны/Модели/exhauster_4_2_8JLWrlAyC98J6a10V9oBqpJ5",
    linkName: "exhauster_4_2",
    linkPath: "СПА/Шаблоны/exhauster_4_2",
    modelsId: [191],
    isTemplate: true,
  },
  {
    id: 121,
    usedUId: 0,
    name: "эксгаустер 7-1_BWBYdSTafQzkcBZsCU2V63p3",
    path: "/home/diaprom/.kvant_remote/СПА/Шаблоны/Модели/эксгаустер 7-1_BWBYdSTafQzkcBZsCU2V63p3",
    linkName: "эксгаустер 7-1",
    linkPath: "СПА/Шаблоны/эксгаустер 7-1",
    modelsId: [195],
    isTemplate: true,
  },
  {
    id: 123,
    usedUId: 0,
    name: "mset_p_AhLaWZjUUei4DxF5YDIa9AKX",
    path: "/home/dmitrii/.kvant_remote/СПА/Проекты/mset_p_AhLaWZjUUei4DxF5YDIa9AKX",
    linkName: "mset_p",
    linkPath: "СПА/Проекты/Ponomarev/mset_p",
    modelsId: [200],
    isTemplate: false,
  },
];
